import Head from "next/head";
import React from "react";

export default function Layout({ children }: {
    children: React.ReactNode
}) {
    return (
        <>
            <Head>
                <title>Search whether an API is available</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#0f3bcd] to-[#252530]">
                {children}
            </main>
        </>
    );
}
