import Head from "next/head";
import React from "react";

export default function Layout({ children }: {
    children: React.ReactNode
}) {
    return (
        <>
            <Head>
                <title>Search whether an API is available</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen bg-gradient-to-b from-[#0f3bcd] to-[#252530]">
                <div className="flex flex-col justify-center md:px-56 px-3">
                    {children}
                </div>
        </main>
        </>
    );
}
